### ISSUE TITLE
need to run patch.py after CM update?

### ISSUE THREAD

**Issue by Diapolo** [moosd/Needle#10]
I'm using CM13 nightlies and I'm asking myself, if it's required to run patch.py after installing a new CM13 update?

Thanks!

**Comment by balazsmezei** [comment]
Yes it is.

**Comment by conorohiggins** [comment]
When I try to run the Python script with my Samsung Galaxy Note 3 N9005 attached, I get this error:

`$:~$ sudo /home/dave/Desktop/patch.py
*** Selected device 9c939e69
 *** Device detected! proceeding...
*** Working dir: /tmp/tmpwbx50i7e
*** Rooting adbd...
adbd is already running as root
remount succeeded
*** Pulling framework from device...
4018 KB/s (5536211 bytes in 1.345s)
*** Disassembling framework...
Error: Unable to access jarfile /home/dave/apktool.jar
*** Done. Now this won't hurt a bit...
Traceback (most recent call last):
File "/home/dave/Desktop/patch.py", line 47, in <module>
f = open(to_patch, "r")
FileNotFoundError: [Errno 2] No such file or directory: 'framework.jar.out/smali/android/content/pm/PackageParser.smali'`

**Comment by Diapolo** [comment]
There is no option for allowing fake sigs under CM13, right? patch.py was running without errors and MicroG settings app is telling me signature spoofing is available. But I can't install FakeStore.

**Comment by souramoo** [comment]
Yes, the update will replace the patched framework with the stock framework with any updates that have been added. You need to patch again to get the updates to framework.jar as well as the signature spoofing.

If microg tells you spoofing is available then it sounds like the patching worked. What error do you get when trying to install FakeStore? Do you have Play Store already installed?

**Comment by Diapolo** [comment]
I'm able to use Play Store, but FakeStore won't install, I assume it's a broken CM install or config. I didn't yet wipe the phone as the rest is working fine :).
