### ISSUE TITLE
Not working on N9005

### ISSUE THREAD

**Issue by conorohiggins** [moosd/Needle#11]
When I try to run the script on my Samsung Galaxy Note 3 LTE (9005), I get this error:

`$:~$ sudo /home/dave/Desktop/patch.py
*** Selected device 9c939e69
 *** Device detected! proceeding...
*** Working dir: /tmp/tmpwbx50i7e
*** Rooting adbd...
adbd is already running as root
remount succeeded
*** Pulling framework from device...
4018 KB/s (5536211 bytes in 1.345s)
*** Disassembling framework...
Error: Unable to access jarfile /home/dave/apktool.jar
*** Done. Now this won't hurt a bit...
Traceback (most recent call last):
File "/home/dave/Desktop/patch.py", line 47, in <module>
f = open(to_patch, "r")
FileNotFoundError: [Errno 2] No such file or directory: 'framework.jar.out/smali/android/content/pm/PackageParser.smali'`

**Comment by conorohiggins** [comment]
CyanogenMod 12.1 on the device

**Comment by balazsmezei** [comment]
It is looking for apktoo.jar in the wrong place. ("Error: Unable to access jarfile /home/dave/apktool.jar")
Cd into /home/dave/Desktop, and then run ./patch.py.

**Comment by conorohiggins** [comment]
Same problem after I cd into Desktop :-/

**Comment by balazsmezei** [comment]
Have you downloaded all the files? Can you paste your whole terminal log when you cd into desktop?

**Comment by conorohiggins** [comment]
Where _should_ it be looking for apktool?

**Comment by conorohiggins** [comment]
I've got it working now, thanks. Your last comment was on the right track - patch.py and apktool weren't in the same folder.
