### ISSUE TITLE
Python script stalls out

### ISSUE THREAD

**Issue by conorohiggins** [moosd/Needle#12]
;Phone is attached and in debug mode. I run the script, and get this

`~$ sudo /home/dave/Downloads/Needle-master/patch.py`

`Enter id of device to target:`

`1 - * daemon started successfully *`

 `2 - List of devices attached`

`3 - 9c928e59`

and nothing more. It is stalled there indefinitely.

**Comment by conorohiggins** [comment]
This issue is fixed by going to Settings > Root access > Enable for ADB on the phone

**Comment by ale5000-git** [comment]
It probably wait for a device that don't exist so it stalls indefinitely, should be fixed by #22
