### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [moosd/Needle#15]

**Comment by ale5000-git** [comment]
@Catfriend1: I don't think this problem is related to #16, please try if it still happens with the latest version.

**Comment by Nutomic** [comment]
I also have an LG H815, running latest CM 13 nightly. Never had any problems applying needle.

**Comment by ale5000-git** [comment]
I will add also an option to create a flashable zip to Tingle in the future,I just don't have the time yet.

**Comment by ghost** [comment]
please delete issue
