### ISSUE TITLE
Regression: Pushing changes fails with device not found

### ISSUE THREAD

**Issue by okias** [moosd/Needle#26]
After last changes, reverting to 99343001a17527a22715e436c5fa8658c6263a84 solve issue.

Something around adb check must broken later workflow...

 **\* Putting things back like nothing ever happened...
updating: classes.dex (deflated 60%)
 **\* Pushing changes to device...
error: device '5693a2e4' not found
Traceback (most recent call last):
  File "./patch.py", line 138, in <module>
    subprocess.check_output(["adb", "-s", chosen_one, "push", "framework.jar", "/system/framework/framework.jar"])
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['adb', '-s', '5693a2e4', 'push', 'framework.jar', '/system/framework/framework.jar']' returned non-zero exit status 1

**Comment by ale5000-git** [comment]
Nothing is changed in the code regarding adb push, are you sure it wasn't just a one time error caused by particular circumstances?
Can you reproduce it many times?

**Comment by okias** [comment]
3 times, tried connect & disconnect phone.

After reverting, first try was OK. Not even reconnected phone before.

**Comment by ale5000-git** [comment]
Try the latest version with just this line removed: `process = subprocess.call([program, "-h"], stdout=DEVNULL, stderr=DEVNULL)`.
I suspect it is related.

**Comment by souramoo** [comment]
The later commits (with patches from @ale5000-git ) should no longer run `-h` to check if a program exists, please could you confirm whether your issue is fixed?

**Comment by okias** [comment]
Fixed, thank you!
