### ISSUE TITLE
Regression: java -jar fails

### ISSUE THREAD

**Issue by okias** [moosd/Needle#27]
> $ ./patch.py 
>  **\* Selected device 5693a2e4
>  **\* Device detected! proceeding...
>  **\* Working dir: /tmp/tmpf8dvncua
>  **\* Rooting adbd...
> restarting adbd as root
> remount succeeded
>  **\* Pulling framework from device...
> 3624 KB/s (5973800 bytes in 1.609s)
>  **\* Disassembling framework...
> I: Using Apktool 2.2.0 on framework.jar
> I: Baksmaling classes.dex...
> I: Baksmaling classes2.dex...
> I: Copying assets and libs...
> I: Copying unknown files...
> I: Copying original files...
>  **\* Done. Now this won't hurt a bit...
>  **\* Injection successful. Reassembling smali...
> I: Using Apktool 2.2.0
> I: Checking whether sources has changed...
> I: Smaling smali folder into classes.dex...
> I: Checking whether sources has changed...
> I: Smaling smali_classes2 folder into classes2.dex...
> W: Could not find resources
> I: Building apk file...
> Exception in thread "main" brut.androlib.AndrolibException: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_2477187644452509808.tmp, p, -F, /tmp/tmpf8dvncua/framework.jar.out/dist/framework.jar, -0, arsc, /tmp/tmpf8dvncua/framework.jar.out/build/apk]
>         at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:439)
>         at brut.androlib.Androlib.buildApk(Androlib.java:670)
>         at brut.androlib.Androlib.build(Androlib.java:310)
>         at brut.androlib.Androlib.build(Androlib.java:263)
>         at brut.apktool.Main.cmdBuild(Main.java:224)
>         at brut.apktool.Main.main(Main.java:84)
> Caused by: brut.common.BrutException: could not exec: [/tmp/brut_util_Jar_2477187644452509808.tmp, p, -F, /tmp/tmpf8dvncua/framework.jar.out/dist/framework.jar, -0, arsc, /tmp/tmpf8dvncua/framework.jar.out/build/apk]
>         at brut.util.OS.exec(OS.java:97)
>         at brut.androlib.res.AndrolibResources.aaptPackage(AndrolibResources.java:433)
>         ... 5 more
> Caused by: java.io.IOException: Cannot run program "/tmp/brut_util_Jar_2477187644452509808.tmp": error=2, No such file or directory
>         at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
>         at brut.util.OS.exec(OS.java:90)
>         ... 6 more
> Caused by: java.io.IOException: error=2, No such file or directory
>         at java.lang.UNIXProcess.forkAndExec(Native Method)
>         at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
>         at java.lang.ProcessImpl.start(ProcessImpl.java:134)
>         at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
>         ... 7 more
> Traceback (most recent call last):
>   File "./patch.py", line 144, in <module>
>     subprocess.check_call(["java", "-jar", SCRIPT_DIR+"/apktool.jar", "b", "framework.jar.out"])
>   File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
>     raise CalledProcessError(retcode, cmd)
> subprocess.CalledProcessError: Command '['java', '-jar', '/home/okias/projects/Needle/apktool.jar', 'b', 'framework.jar.out']' returned non-zero exit status 1

**Comment by okias** [comment]
commit "Replaced subprocess.call with subprocess.check_call" 959cbec2a980fb966cf5b570c51c67988f6a05d4 makes patch.py stop at this point.

Otherwise, it finish and signature spoofing works. Anyway, still, this error is annoying.

**Comment by ale5000-git** [comment]
I think it is a bug in apktool (I'm not sure).
If you post your framework.jar I can see if there is a way to bypass the problem.

**Comment by souramoo** [comment]
Latest commit should now be using smali/baksmali to bypass all apktool-related resource compilation issues. Please try this to see if the error is there.

**Comment by ale5000-git** [comment]
@moosd: Read the e-mail, it is important.

**Comment by okias** [comment]
Fixed!

Good work, thank you.
