### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by Diapolo** [moosd/Needle#37]
I intend to use this with LineageOS, so did anyone use it with LoS13 yet?

Thanks,
Dia

**Comment by Diapolo** [comment]
I can confirm it's still working with LineageOS13 for me, a little sad to see there was no development progress here for 8 months!

**Comment by ale5000-git** [comment]
@Diapolo: If you need something there is also my [fork](https://github.com/ale5000-git/tingle) that is updated more frequently.

**Comment by Diapolo** [comment]
@ale5000-git I'm using your fork already, thanks for maintaining it :).
