### ISSUE TITLE
How do I give adb root access?

### ISSUE THREAD

**Issue by nicolasmaia** [moosd/Needle#38]
In the docs this was not very clear to me, as there is no option to do it from Developer Settings. Should it be done from the terminal, the sudo app...? My phone is a 4.4 Kit Kat

**Comment by nicolasmaia** [comment]
Apparently it's not possible from the stock ROM. It'd be neat to have that clarified in the docs.

**Comment by Lanchon** [comment]
your stock rom, whatever it is, is probably odexed. so adb root is the least of your troubles.

**Comment by ale5000-git** [comment]
@picsi: My [fork](https://github.com/ale5000-git/tingle) have a workaround for rooting adb, provided you have rooted your stock ROM (there are a lot of guides over the internet to root a ROM).

**Comment by nicolasmaia** [comment]
Thanks!
